### ISSUE TITLE
Can Travis cache Maven dependencies?

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#83]
```yaml
cache:
  directories:
    - $HOME/.m2
```

Might improve build speed?
